hw-13/classes/urls.py
from django.urls import path

from teachers.urls import app_name
from .views import class_view, class_delete, change_teacher, show_classes_teacher

app_name = 'classes'

urlpatterns = [
    path('', class_view, name='class_view'),
    path('<int:pk>/', class_view, name='class_view'),
    path('delete/<int:pk>/', class_delete, name='class_delete'),
    path('with_teacher/', show_classes_teacher, name='show_classes_teacher'),
    path('with_teacher/<int:pk>', show_classes_teacher, name='show_classes_teacher'),
    # path('with_teacher', class_view, name='class_view'),
    path('change_teacher/<int:pk>/<int:tpk>', change_teacher, name='change_teacher'),
]

hw-13/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('classes/', include('classes.urls', namespace='classes.classes')),
    path('classboard/', include('classboard.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    
    path("logout/", LogoutView.as_view(template_name="wages_index.html"), name="logout"),
    path("login/", admin.site.urls, name="login"),
    # path("login/", LoginView.as_view(), name="login"),
    
    path('__debug__/', include('debug_toolbar.urls')),
]

hw-13/teachers/urls.py
from django.urls import path
from .views import view_teachers

app_name = 'teachers'

urlpatterns = [
    path('', view_teachers, name='view_teachers'),
    path('<int:pk>/', view_teachers, name='view_teacher'),
    path('create/', view_teachers, name='view_teacher'),
]

hw-13/wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    # общая таблица зарплаты всех учителей
    path('', show_teachers_grid, name='show_teachers_grid'),
    # почему то этот путь не работает, скорее всего из-за того что в views внутри функции show_teachers_grid
    # прописан только 1 случай если нет pk. не учитывается случай когда передается pk. но в шаблоне
    # href="{% url 'wages:show_teachers_grid' teacher_item.pk %}
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    # путь для пересчета з.п. учителя
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

hw-13/templates/layout/base.html
{% url 'teachers:view_teachers' as view_teachers %}
{% url 'classes:class_view' as class_view %}
{% url 'wages:show_teachers_grid' as show_teachers_grid %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Главная{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class='header'>
            {% include 'layout/nav.html' %}
        </div>

        {% block content %}{% endblock content %}
        </div>
    </body>
</html>

hw-13/templates/layout/nav.html
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'classboard_view' %}">Классная доска</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == view_teachers %}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'teachers:view_teachers' %}">Учителя</a>
            </li>
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == class_view %}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'classes:class_view' %}">Предметы</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.path == show_teachers_grid %}
                        active
                    {% endif %}
                        " aria-current="page" href="{% url 'wages:show_teachers_grid' %}">Ведомость</a>
                </li>
            {% endif %}
        </ul>
        {% if not user.is_authenticated %}
            <a class="btn btn-outline-success me-2" href="{% url 'login' %}" type="button">Войти</a>
        {% else %}
            <a class="btn btn-outline-success me-2" href="{% url 'logout' %}" type="button">Выйти</a>
        {% endif %}
    </div>
</nav>