hw-13/classes/urls.py
from django.urls import path

from teachers.urls import app_name
from .views import class_view, class_delete, change_teacher, show_classes_teacher

app_name = 'classes'

urlpatterns = [
    path('', class_view, name='class_view'),
    path('<int:pk>/', class_view, name='class_view'),
    path('delete/<int:pk>/', class_delete, name='class_delete'),
    path('with_teacher/', show_classes_teacher, name='show_classes_teacher'),
    path('with_teacher/<int:pk>', show_classes_teacher, name='show_classes_teacher'),
    # path('with_teacher', class_view, name='class_view'),
    path('change_teacher/<int:pk>/<int:tpk>', change_teacher, name='change_teacher'),
]

hw-13/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('classes/', include('classes.urls', namespace='classes.classes')),
    path('classboard/', include('classboard.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    
    path("logout/", LogoutView.as_view(template_name="wages_index.html"), name="logout"),
    path("login/", admin.site.urls, name="login"),
    # path("login/", LoginView.as_view(), name="login"),
    
    path('__debug__/', include('debug_toolbar.urls')),
]

hw-13/wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    # общая таблица зарплаты всех учителей
    path('', show_teachers_grid, name='show_teachers_grid'),
    # почему то этот путь не работает, скорее всего из-за того что в views внутри функции show_teachers_grid
    # прописан только 1 случай если нет pk. не учитывается случай когда передается pk. но в шаблоне
    # href="{% url 'wages:show_teachers_grid' teacher_item.pk %}
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    # путь для пересчета з.п. учителя
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

hw-13/classes/models.py
from django.db import models

# from teachers.models import Teacher

# Create your models here.


class ClassAbstract(models.Model):
    name = models.CharField(verbose_name='Название предмета', max_length=100)
    
    class Meta:
        abstract = True
        
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'
        
    def __str__(self) -> str:
        return f'{self.name}'
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("classes:class_view", kwargs={"pk": self.pk})

class Class(ClassAbstract):
    name = models.CharField(verbose_name='Название предмета', max_length=100)
    
class ClassWithTeacher(ClassAbstract):
    teacher = models.ManyToManyField(to="teachers.Teacher")
    
    class Meta:
       
        verbose_name = 'Занятие + Учителя'
        verbose_name_plural = 'Занятия + Учителя'

hw-13/classes/views.py
from django.shortcuts import render, get_object_or_404

from .models import Class, ClassWithTeacher
from teachers.models import Teacher

from django.db.models import Q

# Create your views here.

def class_view(request, pk=None) -> render:
    if pk:
        template = 'class_detail.html'
        class_ = get_object_or_404(Class, pk=pk)
        context = {
            'class': class_,
        }
    else:
        template = 'classes.html'
        classes = Class.objects.all()
        teachers = Teacher.objects.all()
        context = {
            'classes': classes,
            'teachers': teachers,
        }
        
    return render(request=request, template_name=template, context=context)
    
    
def class_delete(request, pk) -> render:
    template = 'classes.html'
    
    class_ = get_object_or_404(Class, pk=pk)
    
    class_.delete()
    
    classes = Class.objects.all()
        
    context = {
        'classes': classes,
    }
    
    return render(request=request, template_name=template, context=context)
    
def change_teacher(request, pk, tpk) -> render:
    template = 'classes.html'

    
    class_ = get_object_or_404(Class, pk=pk)
    teacher = get_object_or_404(Teacher, pk=tpk)
    
    class_.teacher = teacher
    class_.save()
    
    # class_ = Class.objects.filter(pk=pk).update(teacher=teacher)
    
    classes = Class.objects.all()
    teachers = Teacher.objects.all()

    # teachers = Teacher.objects.filter(Q(pk__lte=3))
    
    context = {
        'classes': classes,
        'teachers': teachers,
    }

    return render(request=request, template_name=template, context=context)

def show_classes_teacher(request, pk=None) -> render:
    if pk:
        template = 'classes_with_teachers_detail.html'
        class_ = get_object_or_404(ClassWithTeacher, pk=pk)
        
        teacher_first_name = []
        q_ = Q(teacher__first_name='Кравец') | Q(teacher__first_name='Макаренко')

        
        for teacher_first_name_item in ClassWithTeacher.objects.filter(teacher__first_name='Кравец').prefetch_related().values('teacher__first_name', 'teacher__last_name'):
        # for teacher_first_name_item in ClassWithTeacher.objects.filter().prefetch_related().values('teacher__first_name', 'teacher__last_name'):
        # for teacher_first_name_item in ClassWithTeacher.objects.filter().prefetch_related().values('teacher__first_name', 'teacher__last_name').distinct():
            teacher_first_name.append(teacher_first_name_item)
        
        context = {
            'class': class_,
            'teacher_first_name': teacher_first_name,
        }
    else:
        template = 'classes_with_teachers.html'
    
     
        # class_.teacher = teacher
        # class_.save()
        
        # class_ = Class.objects.filter(pk=pk).update(teacher=teacher)
        
        classes = ClassWithTeacher.objects.all()
        teachers = Teacher.objects.all()



        # teachers = Teacher.objects.filter(Q(pk__lte=3))
        
        context = {
            'classes': classes,
            'teachers': teachers,
        }

    return render(request=request, template_name=template, context=context)

hw-13/classes/templates/class_detail.html
{% extends "layout/base.html" %}

{% block title %}
    {{ class.name }}
{% endblock title %}
    
{% block content %}
    <h3>{{ class.name }}</h3>
    {{ class.teacher.name }}
    <a class="btn btn-info" href={% url 'classes:class_view' %}>Обратно</a>
{% endblock content %}
    

hw-13/classes/templates/classes.html
{% extends "layout/base.html" %}

{% block title %}
    Занятия
{% endblock title %}
    
{% block content %}
     {% for class in classes %}
        <h3>{{ class.name }} {{ class.teacher }} </h3>
        
        <a class="btn btn-primary" href="{{ class.get_absolute_url }}"> Перейти </a>    
        {% comment %} <a class="btn btn-success" href="{% url 'classes:class_view' class.pk %}"> Перейти </a>     {% endcomment %}
        <a class="btn btn-danger" href="{% url 'classes:class_delete' class.pk %}"> Удалить </a>    

            {% for teacher in teachers %}
                <p><a class="btn btn-success" href="{% url 'classes:change_teacher' class.pk teacher.pk %}"> Поменять на {{  teacher.last_name }} </a></p>
            {% endfor %}

     {% endfor %}
    
{% endblock content %}

hw-13/classes/templates/classes_with_teachers.html
{% extends "layout/base.html" %}

{% block title %}
    Занятия
{% endblock title %}
    
{% block content %}
     {% for class in classes %}
        <h3>{{ class.name }}</h3>
        <h4>Преподаватели: </h4>

        {% for teacher in class.teacher.all %}
        <p>
            {{ teacher.first_name }} {{ teacher.last_name }}
        </p>
        {% endfor %}
        <a class="btn btn-primary" href="{% url 'classes:show_classes_teacher' class.pk %}"> Перейти </a>    
        {% comment %} <a class="btn btn-success" href="{% url 'classes:class_view' class.pk %}"> Перейти </a>     {% endcomment %}
        <a class="btn btn-danger" href="{% url 'classes:class_delete' class.pk %}"> Удалить </a>    


     {% endfor %}
    
{% endblock content %}

hw-13/classes/templates/classes_with_teachers_detail.html
{% extends "layout/base.html" %}

{% block title %}
    Занятие с учителем
{% endblock title %}
    
{% block content %}

        <h3>{{ class.name }}</h3>
        <h4>Преподаватели: </h4>
        {% for item in teacher_first_name %}

        <p>
            {{ item.teacher__first_name }} {{ item.teacher__last_name }}
        </p>
        {% endfor %}

        <a class="btn btn-primary" href="{% url 'classes:show_classes_teacher' %}"> Перейти </a>    
        {% comment %} <a class="btn btn-success" href="{% url 'classes:class_view' class.pk %}"> Перейти </a>     {% endcomment %}

    
{% endblock content %}